name: "Build and Test"

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn
      - run: yarn bootstrap
      - run: yarn lint
      - run: yarn test
      - run: yarn rebuild
